INSERT INTO "BlogPost" (
  "id",
  "slug",
  "title",
  "excerpt",
  "category",
  "readTimeMinutes",
  "publishedAt",
  "authorName",
  "authorRole",
  "tags",
  "status",
  "body",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'blog-1',
    'membangun-mesin-penulisan-fokus-tanpa-distraksi',
    'Membangun mesin penulisan yang fokus tanpa distraksi',
    'Bagaimana kami merancang editor Renunganku supaya terasa seperti menulis di jurnal fisik, bukan di timeline sosial biasa.',
    'ProductAndVision',
    8,
    '2025-01-10T07:00:00Z',
    'Tim Renunganku',
    'Product & Engineering',
    ARRAY['Editor', 'Fokus', 'Experimen']::TEXT[],
    'PUBLISHED',
    '# Membangun mesin penulisan yang fokus tanpa distraksi\n\nKonten lengkap artikel ini akan dikembangkan langsung dari pengalaman membangun editor Renunganku.',
    NOW(),
    NOW()
  ),
  (
    'blog-2',
    'arsitektur-sosial-yang-ramah-ketidaksempurnaan',
    'Arsitektur sosial yang ramah ketidaksempurnaan',
    'Kenapa feed kami menghindari angka besar dan ranking publik, serta apa dampaknya ke desain database dan API.',
    'Engineering',
    10,
    '2025-01-15T07:00:00Z',
    'Tim Backend',
    'Platform Engineering',
    ARRAY['Backend', 'Desain Sistem', 'Etika']::TEXT[],
    'DRAFT',
    '# Arsitektur sosial yang ramah ketidaksempurnaan\n\nTulisan ini akan menjelaskan prinsip desain arsitektur sosial di Renunganku.',
    NOW(),
    NOW()
  ),
  (
    'blog-3',
    'bahasa-desain-untuk-ruang-digital-yang-tenang',
    'Bahasa desain untuk ruang digital yang tenang',
    'Panduan internal warna, tipografi, dan komponen UI yang kami gunakan untuk menjaga nuansa tenang di seluruh produk.',
    'Design',
    7,
    '2024-12-20T07:00:00Z',
    'Tim Desain',
    'Product Design',
    ARRAY['UI', 'Brand', 'Guidelines']::TEXT[],
    'PUBLISHED',
    '# Bahasa desain untuk ruang digital yang tenang\n\nDokumen ini menjadi dasar sistem desain internal Renunganku.',
    NOW(),
    NOW()
  ),
  (
    'blog-4',
    'metrik-yang-tidak-kami-kejar-di-renunganku',
    'Metrik yang tidak kami kejar di Renunganku',
    'Mengapa kami lebih peduli pada kualitas refleksi daripada jumlah like, dan bagaimana itu tercermin di dashboard internal.',
    'Culture',
    5,
    '2026-01-01T07:00:00Z',
    'Founding Team',
    'Culture & Strategy',
    ARRAY['Culture', 'Analytics', 'Mindset']::TEXT[],
    'SCHEDULED',
    '# Metrik yang tidak kami kejar di Renunganku\n\nTulisan ini membahas metrik yang sengaja tidak kami optimalkan.',
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO NOTHING;
